### ISSUE TITLE
Giphy.js API Key Revealed 

### ISSUE THREAD

**Issue by Sync-Codes** [chalda/DiscordBot#128]
In you giphy.js file, your api key is out in the open so i think you should fix that xD

**Comment by ScriptKi77y** [comment]
https://giphy.api-docs.io/1.0/sticker/search

it's a public api key though

**Comment by F9Alejandro** [comment]
Should have it as a config thing then, and giphy possibly has a limit per api key. If more people get this then the api key might be reached.

**Comment by F9Alejandro** [comment]
Let me put it this way, was the api key registered under a certain account/individual? or is the api truly public?

The statements above contradict each other, public api key only has certain access NOT all access to an api. Second, most if not all api's require an api key to be registered in order to be used, in order to allow multiple users to make requests without causing a 5xx error (internal server error due to over taxing the system) then there is limits on the amount of requests that can be made during a certain time period (often 1 minute period, some are higher).

If it is the public api beta (for development of apps) there is rate limits in place and SHOULDN'T be used in a live production environment. ___"Please use this key while you develop your application and experiment with your integrations. Note: the public key is subject to rate limit constraints and we do not encourage live production deployments to use the public key."___

Take a look at [Request a Production Key](https://giphy.api-docs.io/1.0/welcome/access-and-api-keys#request-a-production-key) right from their site. It states it is for production use (which is what this technically is).

**Comment by MrARM** [comment]
the issue I see is if you want a key from them you have to reach out to their support team, I don't really think a couple discord bots would break it.

**Comment by Einarin** [comment]
It'd probably be better if there was at least an option to set it like the other api keys. It's super convenient to get started the current way though. Considering it's the key from their example documentation I think it's ok to have it there.

It would be good to at least have an option to let users to set it in auth.json so people have a convenient way to change it, although it's always possible to just edit the source.

As noted above, it's technically a development key, but I suspect total discordbot usage is a rounding error in the traffic they see with that key, and given how minimal the command is anyway I'm not super worried about it.

Thanks for filling the bug though, patches are certainly welcome XD

**Comment by F9Alejandro** [comment]
@MrARM the issue is that this api key isn't just one or two bots, it is the __PUBLIC__ key meaning that it is everyone using it. The limit will be hit faster because of the fact it is exposed for the public to use. __IF__ the api key was requested specifically for the discordbot then it should be absolutely fine, since it isn't though there are times where many people can be making a request at the same time and cause the discordbot to get a 5xx response from the api server. It might not seem like a big deal, but it is when it comes down to what they have stated as proper use of that api key.

Continued use of that key, and they notice that it is constant as if it isn't a developer testing the api, but more like the api key is being used in place of a requested one they could easily block that ip or worse remove that developer api key due to misuse.

**Comment by MrARM** [comment]
I don't really know what giphy's limits are for this. I think its more or less like a few dozen requests a second from one IP, I really don't see that being hit by a discord bot, don't get me wrong, but it doesn't look promising. Also a sidenote, there are currently 23 thousand instances of the key in other GitHub repositories. I think we're in the clear.

**Comment by valkyrienyanko** [comment]
You should take a look at [dotenv](https://www.npmjs.com/package/dotenv).

You create a `.env` file in the root of your project, add it to your `.gitignore` and store all your passwords in it. To access them you would just do `process.env.VARIABLE`. See the link for more info.

**Comment by F9Alejandro** [comment]
Closed due to being stale for half a year.
