### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by thegimliboy** [chalda/DiscordBot#54]
Your Discordlink in your README does not work...

**Comment by chalda** [comment]
ah. i actually just copy pasted the "channel" link which isnt an invite link.. The fact that they always show a 24 hour timer next to those always freaks me out a bit. @Einarin can you put the DawnBot channel discord link in the readme pl0x? Also send it to me because i "left" the server and now have no way of going back. lol

**Comment by Nerdietony** [comment]
same, you should fix that

**Comment by chalda** [comment]
The links now expire after 24 hours..

**Comment by Nerdietony** [comment]
You should set it as forever

**Comment by Einarin** [comment]
I generated a new permanent link. This one should actually work. 04837d620039b0e6453f978479ae0f65cb01de46
